### ISSUE TITLE
question about GetModelSuccess

### ISSUE THREAD

**Issue by thomasfaure** [gkilwein/Rackspace-Cloud-Files#1]
Hello @gkilwein , thank you for your simple lib for rackspace CloudFiles, I have a question : 

what is `GetModelSuccess` function in your code ? 

Thank you :)

**Comment by gkilwein** [comment]
Hi @thomasfaure!  Thanks for pointing that out - I see I neglected to put that in the code. It's a very simple function as follows:
`function GetModelSuccess( $results = null )
{
    $retval = array();
    $retval['success'] = true;
    $retval['results'] = $results;
    return (object)$retval;
}
`

There is a corresponding function for errors as well:
`function GetModelError( $code = NULL, $message = NULL )
{
    $retval = array();
    $retval['success'] = false;
    $retval['code'] = $code;
    $retval['message'] = $message;
    return (object)$retval;
}
`

These functions are used inside of my app's model code for a standard way to indicate success or failure, and include reasons why it failed or the results if it was successful.

I hope this library was helpful for you since it looks like Rackspace abandoned their PHP library.
